### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by aculler** [PaloAltoNetworks/autofocus-client-library#16]
Any plans to add this to PyPi? That would be supremely helpful for deployment.

**Comment by rholloway** [comment]
@adc4392 Thanks for the suggestion. We will look into it. In the meantime, also note you can install using pip directly from github using a format similar to:

pip install git+https://github.com/PaloAltoNetworks/autofocus-client-library.git@master#egg=AutoFocusClientLibrary

https://pip.pypa.io/en/stable/reference/pip_install/#git

Hopefully this will help with deployment in the meantime.

**Comment by adc4392** [comment]
Much appreciated on the fast reply!

That's definitely a good point to make. The the particular use case involves systems that do not have access to GitHub directly but do have access to an internal PyPi mirror. I actually haven't looked into if the PyPi mirror can be made to do something similar to the `git+<githublink>` notation for exceptions, so that's something I can investigate as well.

**Comment by gsrt-tech-svc** [comment]
@aculler We've updated our processes and this library is now available on pypi https://pypi.org/project/autofocus-client-library/
The final python 2.7 release is version 1.3.0 and will not be receiving updates.
The current version 4.0.6 is compatible with python 3.6+
